language: python
python:
  - "2.7"
  - "2.6"

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6

matrix:
  include:
      - python: "3.4"
        env: DJANGO=1.6

install:
  - pip install -r dev_requirements.txt
  - pip install -q Django==$DJANGO
  - python setup.py install
  - pip freeze
script: ./runtests.py
